### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by alexdelorenzo** [epeios-q37/atlas-python#3]
Thanks for your work on Atlastk, it's pretty cool.

I notice that Atlastk is released under the MIT license, but the public server and its code are under the AGPLv3. I interpret the AGPLv3 as requiring the source code of any program running on the server must be made available to users. That interpretation means that any Atlas app code that runs on, and is served by, the AGPLv3 server must make its source code available to users.

Can you clarify on whether your interpretation of the AGPLv3 is different from mine, and if you intend to require that all apps using the Atlas toolkit must be made open source by virtue of being served by an AGPLv3 server?

**Comment by epeios-q37** [comment]
I'm glad you like it.
Although the toolkit, which is coded in pure *Python* (or *Java*, or *Node.js*... depending on the version) does not share any code with the server, which is coded in *C++*, the toolkit is totally dependent from the server because only the server, so far at least, is able to process requests from the toolkit.
Nevertheless, I chose these two licenses precisely because I **do not** intend to require that the source code of an application that would use the toolkit must be made available to users.
Since this does not, a priori, infringe the concerned licenses, and since I am the sole author of both the toolkit and the server, I think my interpretation is authoritative, even if, regarding the licenses, another interpretation can also be considered.
This only concerns the toolkit. The source code of the server, either the original version or a modified version, must be provided to any user who requests it.
I hope this answers your question. If you have any further questions, do not hesitate to ask.
(By the way, I hope you received my e-mail regarding your other question.)

**Comment by epeios-q37** [comment]
The http://atlastk.org website has been updated accordingly.

**Comment by alexdelorenzo** [comment]
Awesome, that answers my question. Thanks!
